version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: admin
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "33066:3306"

volumes:
  dbdata:


